# Generated by Django 5.2.4 on 2025-08-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitasDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('tipo_receita', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('Pix', 'Pix'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=10, null=True)),
                ('total_parcelas', models.PositiveIntegerField(default=1)),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
